Hotfix/change role titles
ubiquitypress/rua pull request #532
Opened 2016-11-01 09:56 UTC by stuartjennings-up

2016-11-03 11:01 UTC, craiga requested changes

2016-11-03 11:01 UTC, craiga commented on src/core/decorators.py
> +			messages.add_message(request, messages.ERROR, 'You need to have Press Editor, Press Editor or Series Editor level permission to view this page.')
"Press Editor, Press Editor or Series Editor"? Should these strings just be "Press Editor or Series Editor" now?

2016-11-03 11:01 UTC, craiga commented on src/core/decorators.py
> +			messages.add_message(request, messages.ERROR, 'You need to have Press Editor, Press Editor or Series Editor level permission to view this page.')
Or are they "book editors" instead of "book managers" now?

2016-11-03 11:01 UTC, craiga commented on src/templates/editor/submission_details.html
> +<h3>BOOK EDITOR
Should this be plural? And where's the closing `h3` tag?

2016-11-03 11:14 UTC, stuartjennings-up commented on src/templates/editor/submission_details.html
> +<h3>BOOK EDITOR
Ah well spotted with the plural. The closing tag is further down as the title includes a link. Will make this more obvious in formatting

2016-11-03 11:15 UTC, stuartjennings-up commented on src/core/decorators.py
> +			messages.add_message(request, messages.ERROR, 'You need to have Press Editor, Press Editor or Series Editor level permission to view this page.')
Yes should be Book Editor, thanks

2016-11-08 10:02 UTC, craiga approved these changes

2016-11-08 10:08 UTC, merged