Hotfix/editorial review changes
ubiquitypress/rua pull request #533
Opened 2016-11-01 10:04 UTC by stuartjennings-up

2016-11-03 11:01 UTC, craiga requested changes

2016-11-03 11:01 UTC, craiga commented on src/core/templatetags/dict_lookup.py
>  import os
Ordering of `import` statements here is a bit all over the place. From https://www.python.org/dev/peps/pep-0008/#imports:

> Imports should be grouped in the following order:
> - standard library imports
> - related third party imports
> - local application/library specific imports
> 
> You should put a blank line between each group of imports.

2016-11-03 11:01 UTC, craiga commented on src/editorialreview/views.py
> -	check = None
It's difficult to tell what's going on here; can you configure PyCharm to not be so fickle with spaces vs. tabs? If not, spaces are a better choice (regardless of what Silicon Valley says).

2016-11-03 11:01 UTC, craiga commented on src/editorialreview/views.py
> -	check = None
https://www.youtube.com/watch?v=SsoOG6ZeyUI

2016-11-03 11:01 UTC, craiga commented on src/templates/core/proposals/view_proposal.html
> +{% if proposal.status = 'accepted' or proposal.status = 'declined'%}
Is there supposed to be something here? If not, should the logic be negated and the heading be moved inside the `if`?

2016-11-03 12:07 UTC, stuartjennings-up commented on src/editorialreview/views.py
> -	check = None
Configured. Should have done it a while ago!

2016-11-03 12:18 UTC, stuartjennings-up commented on src/editorialreview/views.py
> -	check = None
Realised that I didn't actually make any changes to this file, just had to change indents when I temporarily put in a print statement, so nothing to check

2016-11-08 10:07 UTC, craiga approved these changes

2016-11-08 10:09 UTC, merged