fix bug that threw error when registering if interests field empty
ubiquitypress/rua pull request #534
Opened 2016-11-01 10:05 UTC by stuartjennings-up

2016-11-03 11:00 UTC, craiga requested changes

2016-11-03 11:00 UTC, craiga commented on src/core/views.py
> +            display_interests = request.POST.get('interests').split(',')  # To keep interests field filled if validation error is raised.
Should `display_interests` be initialised as an empty list?

2016-11-03 11:53 UTC, stuartjennings-up commented on src/core/views.py
> +            display_interests = request.POST.get('interests').split(',')  # To keep interests field filled if validation error is raised.
This was just cut off!
` display_interests = []

```
if request.method == 'POST':
    form = forms.UserCreationForm(request.POST)
    profile_form = forms.RegistrationProfileForm(request.POST)
    display_interests = request.POST.get('interests').split(',')  # To keep interests field filled if validation error is raised.
```

`

2016-11-08 10:06 UTC, craiga approved these changes

2016-11-08 10:09 UTC, merged